import 'package:flutter/material.dart';

/// kdbx预设icon的对应 [KdbxIcon], 使用index与其对应
enum PresetIcons {
  key(Icons.key), // 0
  world(Icons.language), // 1
  warning(Icons.warning), // 2
  networkServer(Icons.computer), // 3
  markedDirectory(Icons.folder), // 4
  userCommunication(Icons.message), // 5
  parts(Icons.crop_square), // 6
  notepad(Icons.note), // 7
  worldSocket(Icons.laptop_chromebook), // 8
  identity(Icons.perm_identity), // 9
  paperReady(Icons.done), // 10
  digicam(Icons.photo_camera), // 11
  irCommunication(Icons.cast), // 12
  multiKeys(Icons.vpn_key), // 13
  energy(Icons.flash_on), // 14
  scanner(Icons.qr_code_scanner), // 15
  worldStar(Icons.star), // 16
  cdRom(Icons.adjust_rounded), // 17
  monitor(Icons.monitor), // 18
  eMail(Icons.mail), // 19
  configuration(Icons.settings), // 20
  clipboardReady(Icons.content_copy), // 21
  paperNew(Icons.insert_drive_file), // 22
  screen(Icons.desktop_windows), // 23
  energyCareful(Icons.low_priority), // 24
  eMailBox(Icons.inbox), // 25
  disk(Icons.sd_card), // 26
  drive(Icons.drive_file_move), // 27
  paperQ(Icons.question_answer), // 28
  terminalEncrypted(Icons.security), // 29
  console(Icons.code), // 30
  printer(Icons.print), // 31
  programIcons(Icons.extension), // 32
  run(Icons.run_circle_outlined), // 33
  settings(Icons.settings), // 34
  worldComputer(Icons.desktop_mac), // 35
  archive(Icons.archive), // 36
  homebanking(Icons.monetization_on), // 37
  driveWindows(Icons.window), // 38
  clock(Icons.alarm_add), // 39
  eMailSearch(Icons.search), // 40
  paperFlag(Icons.flag), // 41
  memory(Icons.memory), // 42
  trashBin(Icons.delete), // 43
  note(Icons.sticky_note_2), // 44
  expired(Icons.cancel), // 45
  info(Icons.info), // 46
  package(Icons.local_shipping), // 47
  folder(Icons.folder), // 48
  folderOpen(Icons.folder_open), // 49
  folderPackage(Icons.local_offer), // 50
  lockOpen(Icons.lock_open), // 51
  paperLocked(Icons.lock), // 52
  checked(Icons.check_circle), // 53
  pen(Icons.create), // 54
  thumbnail(Icons.photo), // 55
  book(Icons.menu_book_rounded), // 56
  list(Icons.format_list_bulleted), // 57
  userKey(Icons.fingerprint), // 58
  tool(Icons.wallet_travel_rounded), // 59
  home(Icons.home), // 60
  star(Icons.star), // 61
  tux(Icons.android_rounded), // 62
  feather(Icons.mode), // 63
  apple(Icons.apple), // 64
  wiki(Icons.article), // 65
  money(Icons.money_off_csred), // 66
  certificate(Icons.verified_user), // 67
  blackBerry(Icons.phone_android_rounded); // 68

  const PresetIcons(this.icon);
  final IconData icon;
}
